import type { ApiSpec, Operation, Schema } from './openapi.js';
import { titleCase } from '../kernel/text.js';

/**
 * SDK generation.
 *
 * Emits a single self-contained file per language with no runtime dependencies:
 * `fetch` in TypeScript, `urllib` in Python. A generated client that drags in a
 * dependency tree is a client teams refuse to adopt.
 */
export interface GeneratedFile {
  readonly path: string;
  readonly language: 'typescript' | 'python' | 'markdown' | 'shell';
  readonly contents: string;
}

function pascalCase(value: string): string {
  return titleCase(value).replace(/\s+/g, '');
}

function camelCase(value: string): string {
  const pascal = pascalCase(value);
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

function snakeCase(value: string): string {
  return value
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .replace(/[^A-Za-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .toLowerCase();
}

function tsType(schema: Schema | undefined, spec: ApiSpec, depth = 0): string {
  if (!schema || depth > 6) return 'unknown';

  if (schema.$ref) {
    return pascalCase(schema.$ref.replace('#/components/schemas/', ''));
  }
  if (schema.enum && schema.enum.length > 0) {
    return schema.enum.map((value) => (typeof value === 'string' ? `'${value}'` : String(value))).join(' | ');
  }

  const types = Array.isArray(schema.type) ? schema.type : schema.type ? [schema.type] : [];
  const render = (type: string): string => {
    switch (type) {
      case 'string':
        return 'string';
      case 'number':
      case 'integer':
        return 'number';
      case 'boolean':
        return 'boolean';
      case 'null':
        return 'null';
      case 'array':
        return `${tsType(schema.items, spec, depth + 1)}[]`;
      case 'object': {
        if (!schema.properties) return 'Record<string, unknown>';
        const required = new Set(schema.required ?? []);
        const fields = Object.entries(schema.properties).map(([name, property]) => {
          const optional = required.has(name) ? '' : '?';
          const key = /^[A-Za-z_$][\w$]*$/.test(name) ? name : `'${name}'`;
          return `    ${key}${optional}: ${tsType(property, spec, depth + 1)};`;
        });
        return `{\n${fields.join('\n')}\n  }`;
      }
      default:
        return 'unknown';
    }
  };

  const rendered = types.length === 0 ? 'unknown' : types.map(render).join(' | ');
  return schema.nullable && !rendered.includes('null') ? `${rendered} | null` : rendered;
}

function pyType(schema: Schema | undefined, spec: ApiSpec, depth = 0): string {
  if (!schema || depth > 6) return 'Any';
  if (schema.$ref) return `"${pascalCase(schema.$ref.replace('#/components/schemas/', ''))}"`;

  const types = Array.isArray(schema.type) ? schema.type : schema.type ? [schema.type] : [];
  const render = (type: string): string => {
    switch (type) {
      case 'string':
        return 'str';
      case 'integer':
        return 'int';
      case 'number':
        return 'float';
      case 'boolean':
        return 'bool';
      case 'null':
        return 'None';
      case 'array':
        return `List[${pyType(schema.items, spec, depth + 1)}]`;
      case 'object':
        return 'Dict[str, Any]';
      default:
        return 'Any';
    }
  };

  if (types.length === 0) return 'Any';
  if (types.length === 1) {
    const rendered = render(types[0] as string);
    return schema.nullable ? `Optional[${rendered}]` : rendered;
  }
  return `Union[${types.map(render).join(', ')}]`;
}

function successSchema(operation: Operation): Schema | undefined {
  return operation.responses.find((response) => response.status.startsWith('2'))?.schema;
}

function methodName(operation: Operation): string {
  if (operation.id) return camelCase(operation.id);
  return camelCase(`${operation.method}_${operation.path.replace(/[/:]/g, '_')}`);
}

export function generateTypeScriptSdk(spec: ApiSpec): GeneratedFile {
  const lines: string[] = [];
  const className = `${pascalCase(spec.info.title)}Client`;

  lines.push(
    '/* eslint-disable */',
    `// Generated by ForgeOS from "${spec.info.title}" v${spec.info.version}.`,
    '// Do not edit by hand — regenerate from the specification instead.',
    '',
    'export interface RequestOptions {',
    '  signal?: AbortSignal;',
    '  headers?: Record<string, string>;',
    '}',
    '',
    'export class ApiError extends Error {',
    '  constructor(',
    '    readonly status: number,',
    '    readonly body: unknown,',
    '    message: string',
    '  ) {',
    '    super(message);',
    "    this.name = 'ApiError';",
    '  }',
    '}',
    ''
  );

  for (const [name, schema] of Object.entries(spec.schemas)) {
    lines.push(`export type ${pascalCase(name)} = ${tsType(schema, spec)};`, '');
  }

  lines.push(
    `export interface ${className}Options {`,
    '  baseUrl?: string;',
    '  /** Sent as an Authorization bearer token. */',
    '  token?: string;',
    '  headers?: Record<string, string>;',
    '  fetch?: typeof fetch;',
    '}',
    '',
    `export class ${className} {`,
    '  private readonly baseUrl: string;',
    '  private readonly token?: string;',
    '  private readonly headers: Record<string, string>;',
    '  private readonly fetchImpl: typeof fetch;',
    '',
    `  constructor(options: ${className}Options = {}) {`,
    `    this.baseUrl = (options.baseUrl ?? '${spec.servers[0]?.url ?? '/'}').replace(/\\/$/, '');`,
    '    this.token = options.token;',
    '    this.headers = options.headers ?? {};',
    '    this.fetchImpl = options.fetch ?? fetch;',
    '  }',
    '',
    '  private async request<T>(',
    '    method: string,',
    '    path: string,',
    '    query?: Record<string, unknown>,',
    '    body?: unknown,',
    '    options: RequestOptions = {}',
    '  ): Promise<T> {',
    '    const url = new URL(this.baseUrl + path, this.baseUrl || undefined);',
    '    for (const [key, value] of Object.entries(query ?? {})) {',
    '      if (value !== undefined && value !== null) url.searchParams.set(key, String(value));',
    '    }',
    '',
    '    const response = await this.fetchImpl(url.toString(), {',
    '      method,',
    '      headers: {',
    "        'content-type': 'application/json',",
    '        ...this.headers,',
    '        ...(this.token ? { authorization: `Bearer ${this.token}` } : {}),',
    '        ...options.headers,',
    '      },',
    '      ...(body !== undefined ? { body: JSON.stringify(body) } : {}),',
    '      ...(options.signal ? { signal: options.signal } : {}),',
    '    });',
    '',
    "    const text = await response.text();",
    '    const parsed = text ? safeJson(text) : null;',
    '    if (!response.ok) {',
    '      throw new ApiError(response.status, parsed, `${method} ${path} failed with ${response.status}`);',
    '    }',
    '    return parsed as T;',
    '  }',
    ''
  );

  for (const operation of spec.operations) {
    const pathParams = (operation.parameters ?? []).filter((parameter) => parameter.in === 'path');
    const queryParams = (operation.parameters ?? []).filter((parameter) => parameter.in === 'query');

    const args: string[] = pathParams.map(
      (parameter) => `${camelCase(parameter.name)}: ${tsType(parameter.schema, spec)}`
    );
    if (operation.requestBody) {
      args.push(`body: ${tsType(operation.requestBody.schema, spec)}`);
    }
    if (queryParams.length > 0) {
      const fields = queryParams
        .map(
          (parameter) =>
            `${camelCase(parameter.name)}${parameter.required ? '' : '?'}: ${tsType(parameter.schema, spec)}`
        )
        .join('; ');
      args.push(`query${queryParams.some((p) => p.required) ? '' : '?'}: { ${fields} }`);
    }
    args.push('options?: RequestOptions');

    const returnType = tsType(successSchema(operation), spec) || 'unknown';
    const pathExpression = pathParams.reduce(
      (accumulator, parameter) =>
        accumulator.replace(
          `:${parameter.name}`,
          `\${encodeURIComponent(String(${camelCase(parameter.name)}))}`
        ),
      operation.path
    );

    if (operation.summary || operation.description) {
      lines.push('  /**');
      if (operation.summary) lines.push(`   * ${operation.summary}`);
      if (operation.description) lines.push(`   * ${operation.description.replace(/\n/g, ' ')}`);
      lines.push('   */');
    }

    const queryArgument =
      queryParams.length > 0
        ? `{ ${queryParams.map((p) => `'${p.name}': query${queryParams.some((q) => q.required) ? '' : '?'}.${camelCase(p.name)}`).join(', ')} }`
        : 'undefined';

    lines.push(
      `  async ${methodName(operation)}(${args.join(', ')}): Promise<${returnType}> {`,
      `    return this.request<${returnType}>('${operation.method.toUpperCase()}', \`${pathExpression}\`, ${queryArgument}, ${operation.requestBody ? 'body' : 'undefined'}, options);`,
      '  }',
      ''
    );
  }

  lines.push(
    '}',
    '',
    'function safeJson(text: string): unknown {',
    '  try {',
    '    return JSON.parse(text);',
    '  } catch {',
    '    return text;',
    '  }',
    '}',
    ''
  );

  return {
    path: `${snakeCase(spec.info.title) || 'api'}-client.ts`,
    language: 'typescript',
    contents: lines.join('\n'),
  };
}

export function generatePythonSdk(spec: ApiSpec): GeneratedFile {
  const lines: string[] = [];
  const className = `${pascalCase(spec.info.title)}Client`;

  lines.push(
    '"""',
    `Generated by ForgeOS from "${spec.info.title}" v${spec.info.version}.`,
    'Do not edit by hand — regenerate from the specification instead.',
    '"""',
    '',
    'from __future__ import annotations',
    '',
    'import json',
    'import urllib.error',
    'import urllib.parse',
    'import urllib.request',
    'from typing import Any, Dict, List, Optional, Union',
    '',
    '',
    'class ApiError(Exception):',
    '    def __init__(self, status: int, body: Any, message: str) -> None:',
    '        super().__init__(message)',
    '        self.status = status',
    '        self.body = body',
    '',
    '',
    `class ${className}:`,
    '    """Thin, dependency-free client. Uses only the standard library."""',
    '',
    '    def __init__(',
    '        self,',
    `        base_url: str = "${spec.servers[0]?.url ?? '/'}",`,
    '        token: Optional[str] = None,',
    '        headers: Optional[Dict[str, str]] = None,',
    '        timeout: float = 30.0,',
    '    ) -> None:',
    '        self.base_url = base_url.rstrip("/")',
    '        self.token = token',
    '        self.headers = headers or {}',
    '        self.timeout = timeout',
    '',
    '    def _request(',
    '        self,',
    '        method: str,',
    '        path: str,',
    '        query: Optional[Dict[str, Any]] = None,',
    '        body: Any = None,',
    '    ) -> Any:',
    '        url = self.base_url + path',
    '        if query:',
    '            filtered = {k: v for k, v in query.items() if v is not None}',
    '            if filtered:',
    '                url += "?" + urllib.parse.urlencode(filtered)',
    '',
    '        headers = {"content-type": "application/json", **self.headers}',
    '        if self.token:',
    '            headers["authorization"] = f"Bearer {self.token}"',
    '',
    '        data = json.dumps(body).encode("utf-8") if body is not None else None',
    '        request = urllib.request.Request(url, data=data, headers=headers, method=method)',
    '',
    '        try:',
    '            with urllib.request.urlopen(request, timeout=self.timeout) as response:',
    '                raw = response.read().decode("utf-8")',
    '                return json.loads(raw) if raw else None',
    '        except urllib.error.HTTPError as error:',
    '            raw = error.read().decode("utf-8")',
    '            try:',
    '                parsed = json.loads(raw) if raw else None',
    '            except json.JSONDecodeError:',
    '                parsed = raw',
    '            raise ApiError(error.code, parsed, f"{method} {path} failed with {error.code}") from error',
    ''
  );

  for (const operation of spec.operations) {
    const pathParams = (operation.parameters ?? []).filter((parameter) => parameter.in === 'path');
    const queryParams = (operation.parameters ?? []).filter((parameter) => parameter.in === 'query');

    const args = ['self'];
    for (const parameter of pathParams) {
      args.push(`${snakeCase(parameter.name)}: ${pyType(parameter.schema, spec)}`);
    }
    if (operation.requestBody) args.push('body: Dict[str, Any]');
    for (const parameter of queryParams) {
      const type = pyType(parameter.schema, spec);
      args.push(
        parameter.required
          ? `${snakeCase(parameter.name)}: ${type}`
          : `${snakeCase(parameter.name)}: Optional[${type}] = None`
      );
    }

    const pathExpression = pathParams.reduce(
      (accumulator, parameter) =>
        accumulator.replace(`:${parameter.name}`, `{${snakeCase(parameter.name)}}`),
      operation.path
    );

    lines.push(`    def ${snakeCase(methodName(operation))}(${args.join(', ')}) -> Any:`);
    if (operation.summary) lines.push(`        """${operation.summary}"""`);

    const queryDict =
      queryParams.length > 0
        ? `{${queryParams.map((p) => `"${p.name}": ${snakeCase(p.name)}`).join(', ')}}`
        : 'None';

    lines.push(
      '        return self._request(',
      `            "${operation.method.toUpperCase()}",`,
      `            f"${pathExpression}",`,
      `            query=${queryDict},`,
      `            body=${operation.requestBody ? 'body' : 'None'},`,
      '        )',
      ''
    );
  }

  return {
    path: `${snakeCase(spec.info.title) || 'api'}_client.py`,
    language: 'python',
    contents: lines.join('\n'),
  };
}

/** Ready-to-run curl examples, one per operation. */
export function generateCurlExamples(spec: ApiSpec): GeneratedFile {
  const baseUrl = spec.servers[0]?.url ?? 'https://api.example.com';
  const lines: string[] = [
    '#!/usr/bin/env bash',
    `# ${spec.info.title} v${spec.info.version} — request examples`,
    'set -euo pipefail',
    '',
    `BASE_URL="\${BASE_URL:-${baseUrl}}"`,
    'TOKEN="${TOKEN:-}"',
    '',
  ];

  for (const operation of spec.operations) {
    lines.push(`# ${operation.summary ?? `${operation.method.toUpperCase()} ${operation.path}`}`);
    const path = operation.path.replace(/:(\w+)/g, '<$1>');
    const parts = [
      `curl -sS -X ${operation.method.toUpperCase()} "$BASE_URL${path}"`,
      '  -H "content-type: application/json"',
      '  -H "authorization: Bearer $TOKEN"',
    ];
    if (operation.requestBody) parts.push(`  -d '{}'`);
    lines.push(parts.join(' \\\n'), '');
  }

  return { path: 'examples.sh', language: 'shell', contents: lines.join('\n') };
}

/** Human-readable reference documentation for the specification. */
export function generateApiMarkdown(spec: ApiSpec): GeneratedFile {
  const lines: string[] = [`# ${spec.info.title}`, '', `Version \`${spec.info.version}\``, ''];
  if (spec.info.description) lines.push(spec.info.description, '');

  if (spec.servers.length > 0) {
    lines.push('## Servers', '');
    for (const server of spec.servers) {
      lines.push(`- \`${server.url}\`${server.description ? ` — ${server.description}` : ''}`);
    }
    lines.push('');
  }

  const byTag = new Map<string, Operation[]>();
  for (const operation of spec.operations) {
    const tag = operation.tags?.[0] ?? 'default';
    const bucket = byTag.get(tag) ?? [];
    bucket.push(operation);
    byTag.set(tag, bucket);
  }

  for (const [tag, operations] of [...byTag.entries()].sort((a, b) => a[0].localeCompare(b[0]))) {
    lines.push(`## ${titleCase(tag)}`, '');
    for (const operation of operations) {
      lines.push(`### \`${operation.method.toUpperCase()} ${operation.path}\``, '');
      if (operation.summary) lines.push(operation.summary, '');
      if (operation.description) lines.push(operation.description, '');

      if (operation.parameters?.length) {
        lines.push('| Parameter | In | Required | Type |', '| --- | --- | --- | --- |');
        for (const parameter of operation.parameters) {
          lines.push(
            `| \`${parameter.name}\` | ${parameter.in} | ${parameter.required ? 'yes' : 'no'} | ${tsType(parameter.schema, spec)} |`
          );
        }
        lines.push('');
      }

      lines.push('| Status | Description |', '| --- | --- |');
      for (const response of operation.responses) {
        lines.push(`| \`${response.status}\` | ${response.description} |`);
      }
      lines.push('');
    }
  }

  return { path: 'API.md', language: 'markdown', contents: lines.join('\n') };
}

export function generateSdkBundle(spec: ApiSpec): GeneratedFile[] {
  return [
    generateTypeScriptSdk(spec),
    generatePythonSdk(spec),
    generateCurlExamples(spec),
    generateApiMarkdown(spec),
  ];
}
